package com.daesang.sp.reservation.dao.sqls;

public class ProductDaoSql {
	public static final String SELECT_ALL_PRODUCTS = "SELECT "
			+ "product.id AS product_id, "
			+ "display_info.id AS display_info_id, "
			+ "product.description AS product_description, "
			+ "display_info.place_name, "
			+ "product.content AS product_content, "
			+ "file_info.save_file_name AS product_image_url "
			+ "FROM product "
			+ "INNER JOIN display_info "
			+ "ON display_info.product_id = product.id "
			+ "INNER JOIN product_image "
			+ "ON product.id = product_image.product_id "
			+ "INNER JOIN file_info "
			+ "ON product_image.file_id = file_info.id "
			+ "WHERE product_image.type = 'th' "
			+ "LIMIT 4 OFFSET :start;";
	
	public static final String SELECT_PRODUCTS_BY_CATEGORY_ID = "SELECT "
			+ "product.id AS product_id, display_info.id AS display_info_id, product.description AS product_description, display_info.place_name AS place_name, product.content AS product_content, file_info.save_file_name AS product_image_url "
			+ "FROM product "
			+ "INNER JOIN display_info "
			+ "ON display_info.product_id = product.id "
			+ "INNER JOIN product_image "
			+ "ON product.id = product_image.product_id "
			+ "INNER JOIN file_info "
			+ "ON product_image.file_id = file_info.id "
			+ "WHERE product_image.type = 'th' "
			+ "AND category_id = :categoryId "
			+ "LIMIT 4 OFFSET :start;";
			
	public static final String SELECT_ALL_PRODUCT_COUNT = "SELECT "
			+ "COUNT(*) AS total_count "
			+ "FROM product "
			+ "INNER JOIN display_info "
			+ "ON display_info.product_id = product.id "
			+ "INNER JOIN category "
			+ "ON category.id = product.category_id;";
	
	public static final String SELECT_PRODUCT_COUNT_BY_CATEGORY_ID = "SELECT "
			+ "COUNT(*) AS total_count "
			+ "FROM product "
			+ "INNER JOIN display_info "
			+ "ON display_info.product_id = product.id "
			+ "INNER JOIN category "
			+ "ON category.id = product.category_id " 
			+ "WHERE category.id = :categoryId;";
	
	public static final String SELECT_DISPLAY_INFO_BY_PRODUCT_ID = "SELECT "
			+ "display_info.product_id, "
			+ "product.category_id AS category_id, "
			+ "display_info.id AS display_info_id, "
			+ "category.name AS category_name, "
			+ "product.description AS product_description, "
			+ "product.content AS product_content, "
			+ "product.event AS product_event, "
			+ "display_info.opening_hours, "
			+ "display_info.place_name, "
			+ "display_info.place_lot, "
			+ "display_info.place_street, "
			+ "display_info.tel AS telephone, "
			+ "display_info.homepage, "
			+ "display_info.email, "
			+ "display_info.create_date, "
			+ "display_info.modify_date "
			+ "FROM display_info "
			+ "INNER JOIN product "
			+ "ON product.id = display_info.product_id  "
			+ "INNER JOIN category "
			+ "ON product.category_id = category.id  "
			+ "WHERE display_info.id = :displayInfoId;";
	
	public static final String SELECT_PRODUCT_IMAGES = "SELECT "
			+ "product.id AS product_id, "
			+ "product_image.id AS product_image_id, "
			+ "product_image.type AS type, "
			+ "file_info.id AS file_info_id, "
			+ "file_info.file_name, "
			+ "file_info.save_file_name, "
			+ "file_info.content_type, "
			+ "file_info.delete_flag, "
			+ "file_info.create_date, "
			+ "file_info.modify_date "
			+ "FROM product "
			+ "INNER JOIN product_image "
			+ "ON product_image.product_id  = product.id "
			+ "INNER JOIN file_info "
			+ "ON product_image.file_id = file_info.id "
			+ "INNER JOIN display_info "
			+ "ON display_info.product_id = product.id "
			+ "WHERE display_info.id = :displayInfoId "
			+ "AND product_image.type = 'ma';";
	
	public static final String SELECT_DISPLAY_INFO_IMAGE_BY_DISPLAY_INFO_ID = "SELECT "
			+ "display_info_image.id AS display_info_image_id, "
			+ "display_info.id AS display_info_id, "
			+ "display_info_image.file_id, "
			+ "file_info.file_name, "
			+ "file_info.save_file_name, "
			+ "file_info.content_type, "
			+ "file_info.delete_flag, "
			+ "file_info.create_date, "
			+ "file_info.modify_date "
			+ "FROM display_info_image "
			+ "INNER JOIN display_info "
			+ "ON display_info.id = display_info_image.display_info_id "
			+ "INNER JOIN file_info "
			+ "ON display_info_image.file_id = file_info.id "
			+ "WHERE display_info.id = :displayInfoId;";
	
	public static final String SELECT_COMMENTS_BY_DISPLAY_INFO_ID ="SELECT "
			+ "ruc.id AS comment_id, "
			+ "di.product_id, "
			+ "ri.id AS reservation_info_id, "
			+ "ruc.score, "
			+ "ruc.comment, "
			+ "ri.reservation_name, "
			+ "ri.reservation_tel AS reservation_telephone, "
			+ "ri.reservation_email, "
			+ "ri.reservation_date, "
			+ "ruc.create_date, "
			+ "ruc.modify_date "
			+ "FROM reservation_info ri "
			+ "INNER JOIN display_info di  "
			+ "ON ri.display_info_id = di.id "
			+ "INNER JOIN reservation_user_comment ruc  "
			+ "ON ruc.reservation_info_id = ri.id "
			+ "WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_COMMENT_IMAGES_BY_DISPLAY_INFO_ID = "SELECT "
			+ "ruci.id AS image_id, "
			+ "ri.id AS reservation_info_id, "
			+ "ruc.id AS reservation_user_comment_id, "
			+ "fi.id AS file_id, "
			+ "fi.file_name AS file_name, "
			+ "fi.save_file_name, "
			+ "fi.content_type, "
			+ "fi.delete_flag, "
			+ "fi.create_date, "
			+ "fi.modify_date "
			+ "FROM reservation_user_comment_image ruci "
			+ "INNER JOIN reservation_info ri "
			+ "ON ri.id = ruci.reservation_user_comment_id "
			+ "INNER JOIN file_info fi "
			+ "ON fi.id = ruci.file_id "
			+ "INNER JOIN reservation_user_comment ruc "
			+ "ON ruci.reservation_user_comment_id =ruc.id;";
	
	public static final String SELECT_AVERAGE_BY_DISPLAY_INFO_ID = "SELECT "
			+ "AVG(score) AS average_score "
			+ "FROM reservation_user_comment ruc "
			+ "INNER JOIN reservation_info ri "
			+ "ON ri.id = ruc.reservation_info_id "
			+ "INNER JOIN display_info di "
			+ "ON di.id = ri.display_info_id "
			+ "WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_PRODUCT_PRICES_BY_DISPLAY_INFO_ID = "SELECT "
			+ "pp.id AS product_price_id, "
			+ "pp.product_id, "
			+ "pp.price_type_name, "
			+ "pp.price, "
			+ "pp.discount_rate, "
			+ "pp.create_date, "
			+ "pp.modify_date "
			+ "FROM product p "
			+ "INNER JOIN display_info di "
			+ "ON di.product_id = p.id "
			+ "INNER JOIN product_price pp "
			+ "ON pp.product_id = p.id;";	
}
