package com.daesang.sp.reservation.dao.sqls;

public class ProductDetailDaoSql {
	public static final String SELECT_ONE_DISPLAY_INFO = "SELECT"
			+ " di.product_id"
			+ " ,p.category_id AS category_id"
			+ " ,di.id AS display_info_id"
			+ " ,c.name AS category_name"
			+ " ,p.description AS product_description"
			+ " ,p.content AS product_content"
			+ " ,p.event AS product_event"
			+ " ,di.opening_hours"
			+ " ,di.place_name"
			+ " ,di.place_lot"
			+ " ,di.place_street"
			+ " ,di.tel AS telephone"
			+ " ,di.homepage"
			+ " ,di.email"
			+ " ,di.create_date"
			+ " ,di.modify_date"
			+ " ,FROM display_info di"
			+ " INNER JOIN product p"
			+ " ON p.id = di.product_id"
			+ " INNER JOIN category c"
			+ " ON p.category_id = c.id"
			+ " WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_SOME_PRODUCT_IMAGES_BY_DISPLAY_INFO_ID = "SELECT"
			+ " p.id AS product_id"
			+ " ,pi.id AS product_image_id"
			+ " ,pi.type AS type"
			+ " ,fi.id AS file_info_id"
			+ " ,fi.file_name"
			+ " ,fi.save_file_name"
			+ " ,fi.content_type"
			+ " ,fi.delete_flag"
			+ " ,fi.create_date"
			+ " ,fi.modify_date"
			+ " FROM product p"
			+ " INNER JOIN product_image pi"
			+ " ON pi.product_id  = p.id"
			+ " INNER JOIN file_info fi"
			+ " ON pi.file_id = fi.id"
			+ " INNER JOIN display_info di"
			+ " ON di.product_id = p.id"
			+ " WHERE di.id = :displayInfoId"
			+ " AND pi.type = 'ma';";
	
	public static final String SELECT_ONE_DISPLAY_INFO_IMAGE_BY_DISPLAY_INFO_ID = "SELECT"
			+ " dii.id AS display_info_image_id"
			+ " ,di.id AS display_info_id"
			+ " ,dii.file_id"
			+ " ,fi.file_name"
			+ " ,fi.save_file_name"
			+ " ,fi.content_type"
			+ " ,fi.delete_flag"
			+ " ,fi.create_date"
			+ " ,fi.modify_date"
			+ " FROM display_info_image dii"
			+ " INNER JOIN display_info di"
			+ " ON di.id = dii.display_info_id"
			+ " INNER JOIN file_info fi"
			+ " ON dii.file_id = fi.id"
			+ " WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_ALL_COMMENTS_BY_DISPLAY_INFO_ID ="SELECT"
			+ " ruc.id AS comment_id"
			+ " ,di.product_id"
			+ " ,ri.id AS reservation_info_id"
			+ " ,ruc.score"
			+ " ,ruc.comment"
			+ " ,ri.reservation_name"
			+ " ,ri.reservation_tel AS reservation_telephone"
			+ " ,ri.reservation_email"
			+ " ,ri.reservation_date"
			+ " ,ruc.create_date"
			+ " ,ruc.modify_date"
			+ " FROM reservation_info ri"
			+ " INNER JOIN display_info di"
			+ " ON ri.display_info_id = di.id"
			+ " INNER JOIN reservation_user_comment ruc"
			+ " ON ruc.reservation_info_id = ri.id"
			+ " WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_SOME_COMMENT_IMAGES_BY_DISPLAY_INFO_ID = "SELECT"
			+ " ruci.id AS image_id"
			+ " ,ri.id AS reservation_info_id"
			+ " ,ruc.id AS reservation_user_comment_id"
			+ " ,fi.id AS file_id"
			+ " ,fi.file_name AS file_name"
			+ " ,fi.save_file_name"
			+ " ,fi.content_type"
			+ " ,fi.delete_flag"
			+ " ,fi.create_date"
			+ " ,fi.modify_date"
			+ " FROM reservation_user_comment_image ruci"
			+ " INNER JOIN reservation_info ri"
			+ " ON ri.id = ruci.reservation_user_comment_id"
			+ " INNER JOIN file_info fi"
			+ " ON fi.id = ruci.file_id"
			+ " INNER JOIN reservation_user_comment ruc"
			+ " ON ruci.reservation_user_comment_id =ruc.id;";
	
	public static final String SELECT_AVERAGE_BY_DISPLAY_INFO_ID = "SELECT"
			+ " AVG(score) AS average_score"
			+ " FROM reservation_user_comment ruc"
			+ " INNER JOIN reservation_info ri"
			+ " ON ri.id = ruc.reservation_info_id"
			+ " INNER JOIN display_info di"
			+ " ON di.id = ri.display_info_id"
			+ " WHERE di.id = :displayInfoId;";
	
	public static final String SELECT_SOME_PRODUCT_PRICES_BY_DISPLAY_INFO_ID = "SELECT"
			+ " pp.id AS product_price_id"
			+ " ,pp.product_id"
			+ " ,pp.price_type_name"
			+ " ,pp.price"
			+ " ,pp.discount_rate"
			+ " ,pp.create_date"
			+ " ,pp.modify_date"
			+ " FROM product p"
			+ " INNER JOIN display_info di"
			+ " ON di.product_id = p.id "
			+ " INNER JOIN product_price pp"
			+ " ON pp.product_id = p.id;";	
}
