package com.daesang.sp.reservation.dao.sqls;

public class ReservationDaoSql {
	public static final String SELECT_RESERVATIONS_BY_EMAIL = "SELECT"
			+ " ri.cancel_flag AS cancel_yn"
			+ " ,ri.create_date"
			+ " ,ri.display_info_id"
			+ " ,ri.modify_date"
			+ " ,ri.product_id"
			+ " ,ri.reservation_date"
			+ " ,ri.id AS reservation_info_id"
			+ " ,ri.reservation_name "
			+ " FROM reservation_info ri"
			+ " INNER JOIN display_info di"
			+ " ON ri.display_info_id = di.id"
			+ " INNER JOIN product p "
			+ " ON p.id = di.product_id "
			+ " WHERE ri.reservation_email = :reservationEmail;";
	
	public static final String SELECT_DISPLAY_INFO_BY_EMAIL = "SELECT"
			+ " c.id AS category_id"
			+ " ,c.name AS category_name"
			+ " ,di.create_date"
			+ " ,di.id AS display_info_id"
			+ " ,di.email"
			+ " ,di.homepage"
			+ " ,di.modify_date"
			+ " ,di.opening_hours"
			+ " ,di.place_lot"
			+ " ,di.place_name"
			+ " ,di.place_street"
			+ " ,p.content AS product_content"
			+ " ,p.description AS product_description"
			+ " ,p.event AS product_event"
			+ " ,p.id AS product_id"
			+ " ,di.tel AS telephone"
			+ " FROM reservation_info ri"
			+ " INNER JOIN display_info di"
			+ " ON ri.display_info_id = di.id"
			+ " INNER JOIN product p"
			+ " ON p.id = di.product_id"
			+ " INNER JOIN category c"
			+ " ON c.id = p.category_id"
			+ " WHERE ri.reservation_email = :reservationEmail;";
	
	public static final String SELECT_TOTAL_PRICE_BY_EMAIL = "SELECT"
			+ " SUM(price)"
			+ " FROM reservation_info ri"
			+ " INNER JOIN product_price pp"
			+ " ON pp.product_id = ri.product_id"
			+ " WHERE reservation_email = :reservationEmail;";
	
	public static final String UPDATE_RESERVATION_STATUS_BY_RESERVATION_INFO_ID = "UPDATE"
			+ " reservation_info ri"
			+ " SET"
			+ " ri.cancel_flag = 1"
			+ " ,ri.modify_date = NOW()"
			+ " WHERE ri.id = :reservationInfoId";
	
	public static final String SELECT_RESERVATION_BY_RESERVATION_INFO_ID = "SELECT"
			+ " ri.id AS reservation_info_id"
			+ " ,ri.create_date"
			+ " ,ri.modify_date"
			+ " ,ri.display_info_id"
			+ " ,ri.product_id"
			+ " ,ri.reservation_date"
			+ " ,ri.reservation_email"
			+ " ,ri.reservation_name"
			+ " ,ri.cancel_flag AS cancel_yn"
			+ " ,ri.reservation_tel AS reservation_telephone"
			+ " FROM reservation_info ri "
			+ " INNER JOIN reservation_info_price rip "
			+ " ON ri.id = rip.reservation_info_id "
			+ " INNER JOIN display_info di"
			+ " ON di.id = ri.display_info_id"
			+ " GROUP BY reservation_info_id"
			+ " HAVING ri.id = :reservationInfoId;";
	
	public static final String SELECT_PRODUCT_PRICES_BY_RESERVATION_ID = "SELECT"
			+ " rip.count"
			+ " ,pp.id"
			+ " ,ri.id AS reservation_info_id"
			+ " ,rip.id AS reservation_info_price_id"
			+ " FROM reservation_info ri"
			+ " INNER JOIN reservation_info_price rip"
			+ " ON rip.reservation_info_id = ri.id"
			+ " INNER JOIN product_price pp"
			+ " ON pp.id = rip.product_price_id"
			+ " WHERE ri.id = :reservationId;";
}
